"""
Content Generator — combines viral trends + all 5 expert knowledge frameworks
to produce a full day's worth of marketing content and copy.
"""

import json
import logging
from pathlib import Path
import anthropic

log = logging.getLogger(__name__)
MODEL = "claude-opus-4-7"

KNOWLEDGE_DIR = Path(__file__).parent.parent / "youtube-knowledge-extractor" / "output"


def load_master_brief() -> str:
    """Load the master marketing engine brief generated by the extraction bot."""
    brief_path = KNOWLEDGE_DIR / "marketing-engine-master-brief.md"
    if brief_path.exists():
        return brief_path.read_text()
    return ""


def load_creator_profiles() -> dict:
    """Load all individual creator knowledge profiles."""
    profiles = {}
    for creator_dir in KNOWLEDGE_DIR.iterdir():
        if creator_dir.is_dir():
            profile_path = creator_dir / "knowledge_profile.json"
            if profile_path.exists():
                with open(profile_path) as f:
                    profiles[creator_dir.name] = json.load(f)
    return profiles


def generate_daily_content_package(
    client: anthropic.Anthropic,
    viral_intelligence: dict,
    business_context: dict,
) -> dict:
    """
    Generate a full day's content package:
    - 3 social media posts (Instagram/LinkedIn/Facebook)
    - 1 email to list
    - 1 YouTube/video script hook + outline
    - 3 short-form video scripts (Reels/TikTok)
    - 5 content hooks for tomorrow
    - 1 sales/offer post
    """
    master_brief = load_master_brief()
    brief_snippet = master_brief[:6000] if master_brief else "No brief loaded yet — run the extraction bot first."

    biz_name = business_context.get("business_name", "House of AI™")
    offer = business_context.get("core_offer", "AI-powered business coaching for women")
    audience = business_context.get("dream_client", "women entrepreneurs ready to scale with AI")
    cta = business_context.get("call_to_action", "DM me 'AI' to learn more")

    todays_topics = viral_intelligence.get("todays_topics", [])
    viral_angles = viral_intelligence.get("viral_angles", [])
    hook_patterns = viral_intelligence.get("hook_patterns", [])

    prompt = f"""You are the AI Marketing Employee for {biz_name}.

## YOUR PROGRAMMING (Expert Frameworks)
{brief_snippet}

## TODAY'S VIRAL INTELLIGENCE
Top trending angles: {viral_angles}
Proven hook patterns: {hook_patterns}
Today's hot topics: {json.dumps(todays_topics, indent=2)}

## BUSINESS CONTEXT
Business: {biz_name}
Core Offer: {offer}
Dream Client: {audience}
Call to Action: {cta}

## YOUR TASK
Generate today's complete content package. Apply ALL frameworks:
- Chase Hughes: embed buyer psychology triggers and behavioral language
- Leanne Mosley: use premium identity-elevation messaging
- Brooke Shelton: use proven content structure and hooks
- Russell Brunson: apply hook-story-offer and funnel logic
- Melanie Ann Layer: use desire-based, feminine power language
- Ray CFU: use viral formats and engagement-driving patterns

Return a JSON object:
{{
  "date_generated": "today",
  "theme_of_the_day": "the unifying theme across all content today",
  "social_posts": [
    {{
      "platform": "Instagram",
      "format": "carousel | single image | reel caption",
      "hook": "the opening line",
      "body": "full post body",
      "cta": "call to action",
      "hashtags": ["tag1", "tag2"],
      "psychology_trigger_used": "which Chase Hughes trigger is embedded"
    }},
    {{
      "platform": "LinkedIn",
      "format": "text post",
      "hook": "the opening line",
      "body": "full post body",
      "cta": "call to action",
      "psychology_trigger_used": "which trigger is embedded"
    }},
    {{
      "platform": "Facebook",
      "format": "story post",
      "hook": "the opening line",
      "body": "full post body",
      "cta": "call to action",
      "psychology_trigger_used": "which trigger is embedded"
    }}
  ],
  "email": {{
    "subject_line": "email subject",
    "preview_text": "preview snippet",
    "body": "full email body with greeting, story, offer, and CTA",
    "ps_line": "the P.S. line",
    "funnel_stage": "cold | warm | hot"
  }},
  "video_content": {{
    "youtube_hook": "first 30 seconds script",
    "youtube_outline": ["point 1", "point 2", "point 3", "point 4", "CTA"],
    "reels": [
      {{"hook": "opening line", "script": "15-30 second full script", "format": "talking head | text overlay | b-roll"}},
      {{"hook": "opening line", "script": "15-30 second full script", "format": "talking head | text overlay | b-roll"}},
      {{"hook": "opening line", "script": "15-30 second full script", "format": "talking head | text overlay | b-roll"}}
    ]
  }},
  "sales_post": {{
    "platform": "Instagram or Facebook",
    "hook": "attention-grabbing open",
    "story": "epiphany bridge / origin story moment",
    "offer_reveal": "the offer and what they get",
    "stack": "the value stack breakdown",
    "urgency": "urgency or scarcity element",
    "cta": "specific call to action"
  }},
  "tomorrow_hooks": [
    "Hook idea 1 for tomorrow",
    "Hook idea 2 for tomorrow",
    "Hook idea 3 for tomorrow",
    "Hook idea 4 for tomorrow",
    "Hook idea 5 for tomorrow"
  ]
}}

Only return valid JSON. Make every word count. Write like a 7-figure marketer."""

    message = client.messages.create(
        model=MODEL,
        max_tokens=8192,
        messages=[{"role": "user", "content": prompt}],
    )

    raw = message.content[0].text.strip()
    if raw.startswith("```"):
        raw = raw.split("```")[1]
        if raw.startswith("json"):
            raw = raw[4:]

    return json.loads(raw)


def format_content_as_markdown(content_package: dict) -> str:
    """Format the daily content package as readable markdown for review."""
    lines = [
        f"# Daily Content Package\n",
        f"**Theme of the Day:** {content_package.get('theme_of_the_day', '')}\n",
        "---\n",
        "## Social Posts\n",
    ]

    for post in content_package.get("social_posts", []):
        lines += [
            f"### {post['platform']} — {post['format']}\n",
            f"**Hook:** {post['hook']}\n",
            f"{post['body']}\n",
            f"**CTA:** {post['cta']}\n",
            f"*Psychology trigger: {post.get('psychology_trigger_used', '')}*\n\n",
        ]

    email = content_package.get("email", {})
    lines += [
        "---\n## Email\n",
        f"**Subject:** {email.get('subject_line', '')}\n",
        f"**Preview:** {email.get('preview_text', '')}\n\n",
        f"{email.get('body', '')}\n\n",
        f"**P.S.** {email.get('ps_line', '')}\n",
        f"*Funnel stage: {email.get('funnel_stage', '')}*\n\n",
    ]

    video = content_package.get("video_content", {})
    lines += [
        "---\n## Video Content\n",
        f"### YouTube Hook (first 30 sec)\n{video.get('youtube_hook', '')}\n\n",
        "### YouTube Outline\n",
    ]
    for point in video.get("youtube_outline", []):
        lines.append(f"- {point}\n")

    lines.append("\n### Reels / TikTok Scripts\n")
    for i, reel in enumerate(video.get("reels", []), 1):
        lines += [
            f"**Reel {i} ({reel['format']})**\n",
            f"Hook: {reel['hook']}\n",
            f"{reel['script']}\n\n",
        ]

    sales = content_package.get("sales_post", {})
    lines += [
        "---\n## Sales Post\n",
        f"**Hook:** {sales.get('hook', '')}\n\n",
        f"{sales.get('story', '')}\n\n",
        f"**Offer:** {sales.get('offer_reveal', '')}\n",
        f"**Stack:** {sales.get('stack', '')}\n",
        f"**Urgency:** {sales.get('urgency', '')}\n",
        f"**CTA:** {sales.get('cta', '')}\n\n",
    ]

    lines += [
        "---\n## Tomorrow's Hooks\n",
    ]
    for hook in content_package.get("tomorrow_hooks", []):
        lines.append(f"- {hook}\n")

    return "".join(lines)
