"""
Content Generator — combines viral trends + all 5 expert knowledge frameworks
to produce a full day's worth of marketing content and copy.
"""

import json
import logging
from pathlib import Path
import anthropic

log = logging.getLogger(__name__)
MODEL = "claude-opus-4-7"

KNOWLEDGE_DIR = Path(__file__).parent.parent / "youtube-knowledge-extractor" / "output"


def load_master_brief() -> str:
    """Load the master marketing engine brief generated by the extraction bot."""
    brief_path = KNOWLEDGE_DIR / "marketing-engine-master-brief.md"
    if brief_path.exists():
        return brief_path.read_text()
    return ""


def load_creator_profiles() -> dict:
    """Load all individual creator knowledge profiles."""
    profiles = {}
    for creator_dir in KNOWLEDGE_DIR.iterdir():
        if creator_dir.is_dir():
            profile_path = creator_dir / "knowledge_profile.json"
            if profile_path.exists():
                with open(profile_path) as f:
                    profiles[creator_dir.name] = json.load(f)
    return profiles


def generate_daily_content_package(
    client: anthropic.Anthropic,
    viral_intelligence: dict,
    business_context: dict,
) -> dict:
    """
    Generate a full day's content package using the 5x/day posting schedule:
    - 08:00 Morning Insight (carousel/static)
    - 11:00 Tool Spotlight (Reel)
    - 14:00 Infrastructure BTS (Story/Reel)
    - 17:00 Emotional Hook (Reel)
    - 21:00 Evening CTA (static/Reel)
    - 1 email to list
    - 5 hooks for tomorrow
    """
    master_brief = load_master_brief()
    brief_snippet = master_brief[:6000] if master_brief else "No brief loaded yet — run the extraction bot first."

    brand = business_context.get("brand", {})
    competitors = business_context.get("competitors", {})
    schedule = business_context.get("posting_schedule", {})

    biz_name = brand.get("business_name", "House of AI™")
    offer = str(brand.get("services", "AI-powered business infrastructure for women founders"))
    audience = str(brand.get("dream_client", {}))
    proven_hooks = brand.get("proven_hooks", [])
    ctas = brand.get("ctas", ["DM me 'LEGACY' to learn more"])
    voice_rules = brand.get("brand_voice", [])
    white_space = competitors.get("our_white_space", [])
    daily_slots = schedule.get("daily_slots", [])

    todays_topics = viral_intelligence.get("todays_topics", [])
    viral_angles = viral_intelligence.get("viral_angles", [])
    hook_patterns = viral_intelligence.get("hook_patterns", [])
    visual_assets = business_context.get("visual_assets_available", [])

    asset_section = ""
    if visual_assets:
        asset_list = "\n".join(f"- {a}" for a in visual_assets[:20])
        asset_section = f"""
## PRE-GENERATED VISUAL ASSETS (use these filenames in b_roll_notes)
These cinematic images are already in the library — reference them by filename:
{asset_list}
When writing b_roll_notes, match the closest asset filename to the scene described.
"""

    prompt = f"""You are the AI Marketing Employee for {biz_name} (@house_of_ai.boston).{asset_section}

## YOUR EXPERT PROGRAMMING
{brief_snippet}

## BRAND VOICE RULES (never break these)
{chr(10).join(f"- {r}" for r in voice_rules)}

## OUR WHITE SPACE (what makes us different from everyone else)
{chr(10).join(f"- {w}" for w in white_space)}

## PROVEN HOOKS (use or riff on these)
{chr(10).join(f"- {h}" for h in proven_hooks)}

## TODAY'S VIRAL INTELLIGENCE
Trending angles: {viral_angles}
Hot hook patterns: {hook_patterns}
Today's topics: {json.dumps(todays_topics, indent=2)}

## THE 5x/DAY POSTING SCHEDULE (generate one post per slot)
{json.dumps(daily_slots, indent=2)}

## YOUR TASK
Generate the complete 5x/day content package for @house_of_ai.boston.
Apply ALL six expert frameworks in every piece:
- Chase Hughes: buyer psychology triggers and behavioral compliance language
- Leanne Mosley: premium identity-elevation and queen energy messaging
- Brooke Shelton: proven content structure and hook formulas
- Russell Brunson: hook-story-offer and funnel logic
- Melanie Ann Layer: desire-based feminine power language
- Ray CFU: viral format patterns and engagement drivers

Return a JSON object:
{{
  "date_generated": "today",
  "theme_of_the_day": "the single unifying theme across all 5 posts today",
  "instagram_posts": [
    {{
      "slot_time": "08:00",
      "slot_name": "The Morning Insight",
      "format": "carousel or static",
      "hook": "the opening line — polarizing, high-level",
      "body": "full post body",
      "slide_breakdown": ["Slide 1 text", "Slide 2 text", "Slide 3 text"],
      "cta": "save / share CTA — no direct sell at 8am",
      "hashtags": ["tag1", "tag2", "tag3"],
      "psychology_trigger": "which framework element is embedded"
    }},
    {{
      "slot_time": "11:00",
      "slot_name": "The Tool Spotlight",
      "format": "Reel",
      "hook": "opening line — curiosity-driven, cheat-code energy",
      "script": "full 30-60 second Reel script",
      "b_roll_notes": "what to film or show on screen",
      "cta": "save + follow CTA",
      "hashtags": ["tag1", "tag2", "tag3"],
      "psychology_trigger": "which framework element is embedded"
    }},
    {{
      "slot_time": "14:00",
      "slot_name": "The Infrastructure BTS",
      "format": "Reel or Story",
      "hook": "opening line — aspirational, behind the scenes",
      "script": "full script showing the automated business running",
      "b_roll_notes": "what to film — luxury location + phone showing automations running",
      "cta": "DM keyword CTA",
      "dm_keyword": "LEGACY or SYSTEM",
      "hashtags": ["tag1", "tag2", "tag3"],
      "psychology_trigger": "which framework element is embedded"
    }},
    {{
      "slot_time": "17:00",
      "slot_name": "The Emotional Hook",
      "format": "Reel",
      "hook": "opening line — deep emotional resonance, founder burnout",
      "script": "full 30-60 second Reel script — make them feel deeply seen",
      "b_roll_notes": "what to film",
      "cta": "comment or DM CTA — connection-focused",
      "hashtags": ["tag1", "tag2", "tag3"],
      "psychology_trigger": "which framework element is embedded"
    }},
    {{
      "slot_time": "21:00",
      "slot_name": "The Evening CTA",
      "format": "static or Reel",
      "hook": "direct, bold, income-qualifier hook",
      "body": "full post — short, punchy, lead-gen focused",
      "offer": "specific service or entry point being offered",
      "cta": "direct DM keyword CTA — LEGACY, SYSTEM, or BOT",
      "dm_keyword": "the keyword",
      "hashtags": ["tag1", "tag2", "tag3"],
      "psychology_trigger": "which framework element is embedded"
    }}
  ],
  "email": {{
    "subject_line": "email subject — luxury, curiosity, or identity-based",
    "preview_text": "preview snippet",
    "body": "full email — greeting, story using epiphany bridge, offer, CTA",
    "ps_line": "the P.S. line",
    "funnel_stage": "cold | warm | hot"
  }},
  "tomorrow_hooks": [
    "Hook 1 for tomorrow",
    "Hook 2 for tomorrow",
    "Hook 3 for tomorrow",
    "Hook 4 for tomorrow",
    "Hook 5 for tomorrow"
  ]
}}

Only return valid JSON. Every word must feel luxury, feminine, and authoritative.
Never sound generic, tech-bro, or accessible to everyone."""

    message = client.messages.create(
        model=MODEL,
        max_tokens=8192,
        messages=[{"role": "user", "content": prompt}],
    )

    raw = message.content[0].text.strip()
    if raw.startswith("```"):
        raw = raw.split("```")[1]
        if raw.startswith("json"):
            raw = raw[4:]

    return json.loads(raw)


def format_content_as_markdown(content_package: dict) -> str:
    """Format the daily content package as readable markdown for review."""
    lines = [
        f"# Daily Content Package\n",
        f"**Theme of the Day:** {content_package.get('theme_of_the_day', '')}\n",
        "---\n",
        "## Social Posts\n",
    ]

    for post in content_package.get("social_posts", []):
        lines += [
            f"### {post['platform']} — {post['format']}\n",
            f"**Hook:** {post['hook']}\n",
            f"{post['body']}\n",
            f"**CTA:** {post['cta']}\n",
            f"*Psychology trigger: {post.get('psychology_trigger_used', '')}*\n\n",
        ]

    email = content_package.get("email", {})
    lines += [
        "---\n## Email\n",
        f"**Subject:** {email.get('subject_line', '')}\n",
        f"**Preview:** {email.get('preview_text', '')}\n\n",
        f"{email.get('body', '')}\n\n",
        f"**P.S.** {email.get('ps_line', '')}\n",
        f"*Funnel stage: {email.get('funnel_stage', '')}*\n\n",
    ]

    video = content_package.get("video_content", {})
    lines += [
        "---\n## Video Content\n",
        f"### YouTube Hook (first 30 sec)\n{video.get('youtube_hook', '')}\n\n",
        "### YouTube Outline\n",
    ]
    for point in video.get("youtube_outline", []):
        lines.append(f"- {point}\n")

    lines.append("\n### Reels / TikTok Scripts\n")
    for i, reel in enumerate(video.get("reels", []), 1):
        lines += [
            f"**Reel {i} ({reel['format']})**\n",
            f"Hook: {reel['hook']}\n",
            f"{reel['script']}\n\n",
        ]

    sales = content_package.get("sales_post", {})
    lines += [
        "---\n## Sales Post\n",
        f"**Hook:** {sales.get('hook', '')}\n\n",
        f"{sales.get('story', '')}\n\n",
        f"**Offer:** {sales.get('offer_reveal', '')}\n",
        f"**Stack:** {sales.get('stack', '')}\n",
        f"**Urgency:** {sales.get('urgency', '')}\n",
        f"**CTA:** {sales.get('cta', '')}\n\n",
    ]

    lines += [
        "---\n## Tomorrow's Hooks\n",
    ]
    for hook in content_package.get("tomorrow_hooks", []):
        lines.append(f"- {hook}\n")

    return "".join(lines)
